//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    //using System.ComponentModel.DataAnnotations;

    //[MetadataType(typeof(EmpleadoDataAnnotations))]
    public partial class Empleado
    {
        public int idEmpleado { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Curp { get; set; }
        public string Rfc { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public int idPuesto { get; set; }
    
        public virtual Puesto Puesto { get; set; }
    }
    //public partial class EmpleadoDataAnnotations
    //{
    //    public int idEmpleado { get; set; }
    //    [Required(ErrorMessage = "El Nombre es obligatorio")]
    //    public string Nombre { get; set; }
    //    [Required(ErrorMessage = "El Apellido es obligatorio")]
    //    public string Apellido { get; set; }
    //    [Required(ErrorMessage = "Curp es obligatorio")]
    //    public string Curp { get; set; }
    //    [Required(ErrorMessage = "Rfc es obligatorio")]
    //    public string Rfc { get; set; }
    //    [Required(ErrorMessage = "El Campo es obligatorio")]
    //    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
    //    public System.DateTime fechaNacimiento { get; set; }
    //    [Required(ErrorMessage = "Selecciona una Opcion")]
    //    public int idPuesto { get; set; }

    //    public virtual Puesto Puesto { get; set; }
    //}
}
